version: 2.1
orbs:
  python: circleci/python@0.2.1

commands:
  build_spdb_clib:
    description: "Build spdb's C library"
    steps:
      - run: python setup.py build_ext --inplace

  install:
    description: "Install Python dependencies"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      # Install dependencies for testing.
      - run: pip install --user -r requirements-test.txt
      - python/save-cache

  test_spdb:
    description: "Test spdb"
    steps:
      - run: python3 -m unittest
jobs:
  test_py3_5:
    docker:
      - image: circleci/python:3.5
    environment:
      AWS_ACCESS_KEY_ID: testing
      AWS_SECRET_ACCESS_KEY: testing
      AWS_SECURITY_TOKEN: testing
      AWS_SESSION_TOKEN: testing
    steps:
      - install
      - build_spdb_clib
      - test_spdb

workflows:
  version: 2
  test:
    jobs:
      - test_py3_5
