version: 2.1
orbs:
  python: circleci/python@0.2.1

commands:
  build_spdb_clib:
    description: "Build spdb's C library"
    steps:
      - run: python setup.py build_ext --inplace

  install:
    description: "Install Python dependencies"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      # Install dependencies for testing.
      - run: pip install --user -r requirements-test.txt
      - python/save-cache

  test_spdb:
    description: "Test spdb"
    steps:
      - run: python3 -m unittest
